### ISSUE TITLE
Dependencies missing when running jekyll locally

### ISSUE THREAD

**Issue by r98inver** [stellarvector/blog#1]
I tried to fork and run the blog locally, and I run into a couple of issues. First of all, `jekyll serve` doesn't seem to work, but the error already suggests to use `bundle exec jekyll serve` (or `bundle exec jekyll s`) instead.   
However also `bundle exec` returns an error `cannot load such file -- jekyll-include-cache (LoadError)`. I solved this adding the line `gem 'jekyll-include-cache` to `Gemfile`, then running `bundle update --bundler` and `bundle install`.    
After that another missing dependence: `cannot load such file -- webrick (LoadError)`. For this `bundle add webrick` worked (I think is equivalent to add to the `Gemfile` the line like above). `bundle exec jekyll s` works now, but I don't want to pr this since I'm quite new to gem and I don't want to mess up with the online repo.

**Comment by vikvanderlinden** [comment]
I added `jekyll-include-cache` because that seemed required to be able to run indeed. However, I got no error regarding `webrick` and gh-pages build also seems to work fine without it so not sure why this would be required.
Could you check for the current latest version if the error still occurs on your side?

**Comment by r98inver** [comment]
Yes, i deleted and reinstalled everything but still same issue. It seems an issue with Ruby 3.0: https://github.com/jekyll/jekyll/issues/8523. They suggest to just add webrick
